Implements bounds fun for composition
porterin/kottie pull request #1
Opened 2024-12-21 11:44 UTC by sbajaj-porter

2025-01-10 03:36 UTC, SandeepDhami2242 requested changes

2025-01-10 03:36 UTC, SandeepDhami2242 commented on lib/build.gradle.kts
> +        url.set("https://github.com/sbajaj-porter/kottie/")
why this?

2025-01-10 03:36 UTC, SandeepDhami2242 commented on lib/build.gradle.kts
> +            developerConnection.set("scm:git:ssh://git@github.com:sbajaj-porter/kottie.git")
same, why changes are required here

2025-01-10 03:36 UTC, SandeepDhami2242 commented on lib/src/commonMain/kotlin/kottieComposition/KottieCompositionUtils.kt
> +expect fun bounds(composition: Any?): Rect
why compossition type is Any and not LottieComposition and also nullable?

2025-01-10 03:36 UTC, SandeepDhami2242 commented on lib/src/iosMain/kotlin/kottieComposition/KottieCompositionUtils.ios.kt
> +actual fun bounds(composition: Any?): Rect {
Same why can't we use CompatibleAnimationView and also not nullable

2025-01-10 03:36 UTC, SandeepDhami2242 commented on lib/src/skiaMain/kotlin/kottieComposition/KottieCompositionUtils.skia.kt
what is skia?

2025-01-10 03:36 UTC, SandeepDhami2242 commented on lib/src/androidMain/kotlin/kottieComposition/KottieCompositionUtils.android.kt
> +actual fun bounds(composition: Any?): Rect {
same here

2025-01-10 05:58 UTC, SandeepDhami2242 commented on lib/src/commonMain/kotlin/kottieComposition/KottieCompositionUtils.kt
> +expect fun bounds(composition: Any?): Rect
can we use kottieAnimation expect and its actual as LottieComposition or CompatibleAnimationView based on platform

2025-01-10 06:04 UTC, sbajaj-porter commented on lib/src/commonMain/kotlin/kottieComposition/KottieCompositionUtils.kt
> +expect fun bounds(composition: Any?): Rect
Not possible.
KottieAnimation and KottieComposition are not classes.
These are composable functions.

2025-01-10 06:11 UTC, sbajaj-porter commented on lib/build.gradle.kts
> +            developerConnection.set("scm:git:ssh://git@github.com:sbajaj-porter/kottie.git")
Fixing

2025-01-10 06:11 UTC, sbajaj-porter commented on lib/build.gradle.kts
> +        url.set("https://github.com/sbajaj-porter/kottie/")
Fixing

2025-01-10 06:12 UTC, sbajaj-porter commented on lib/src/iosMain/kotlin/kottieComposition/KottieCompositionUtils.ios.kt
> +actual fun bounds(composition: Any?): Rect {
CompatibleAnimationView is not a common class.

2025-01-10 06:20 UTC, sbajaj-porter commented on lib/src/skiaMain/kotlin/kottieComposition/KottieCompositionUtils.skia.kt
`Skia` is an open source 2D graphics library.

`Kottie` (at the moment) is just a expect/actual wrapper  for mobile and web.
They are also working on its internal renderer based on skia, so it doesn't have to rely on multiple platform specific `Lottie` implementations.

I believe it didn't compile if I didn't implement the actual for this variant.

Jfyi, `Flutter`'s graphic backend is also Skia. So it could be for Flutter also.

2025-01-10 07:01 UTC, sbajaj-porter commented on lib/src/commonMain/kotlin/kottieComposition/KottieCompositionUtils.kt
> +expect fun bounds(composition: Any?): Rect
As discussed, going ahead with typealias *KottieCompositionAnimation*

2025-01-10 09:52 UTC, sbajaj-porter commented on lib/build.gradle.kts
> +        url.set("https://github.com/sbajaj-porter/kottie/")
Fixed

2025-01-10 09:53 UTC, sbajaj-porter commented on lib/build.gradle.kts
> +            developerConnection.set("scm:git:ssh://git@github.com:sbajaj-porter/kottie.git")
Fixed.
Will come in another PR.
Updated to https://github.com/porterin/kottie/

2025-01-10 09:53 UTC, sbajaj-porter commented on lib/src/iosMain/kotlin/kottieComposition/KottieCompositionUtils.ios.kt
> +actual fun bounds(composition: Any?): Rect {
Fixed using expect/actual class

2025-01-10 13:49 UTC, sbajaj-porter commented on lib/src/skiaMain/kotlin/kottieComposition/KottieCompositionUtils.skia.kt
@SandeepDhami2242 Had to implement bounds and fit types for Skia renderer as well.
It was needed for web.
I noticed that shimmers have been introduced in web as well.

2025-01-13 11:50 UTC, SandeepDhami2242 approved these changes

2025-01-15 14:07 UTC, merged